#!/usr/bin/env bash
#MISE description="Ensure i18n catalogs are up to date"
#MISE depends=["lingui"]
set -e

git status --porcelain -- "packages/client/components/i18n/catalogs" | grep -q . && exit 1 || exit 0
