name: Sync Feature Matrix

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Download and parse sheet
        env:
          SHEET_ID: ${{ secrets.FEATURE_MATRIX_SHEET_ID }}
        run: curl -s https://docs.google.com/spreadsheets/d/$SHEET_ID/gviz/tq?tqx=out:html > feature-matrix.html
      - uses: docker://pandoc/core:3.5
        with:
          args: >-
            --to markdown_strict+pipe_tables
            --output=doc/src/feature-matrix.md
            feature-matrix.html
      - name: Clean up the document
        run: |
          # add title
          sed -i "1i# Feature Matrix\nComparison of implemented features across Revolt's clients.\n" doc/src/feature-matrix.md

          # replace the indicators
          sed -i 's/| O /| ✅ /g' doc/src/feature-matrix.md
          sed -i 's/| X /| ❌ /g' doc/src/feature-matrix.md
          sed -i 's/| Partly /| 🚧 /g' doc/src/feature-matrix.md
          sed -i 's/| NoPlan /| ⛔ /g' doc/src/feature-matrix.md

          # remove extra rows
          sed -i '4d' doc/src/feature-matrix.md
          sed -i '4d' doc/src/feature-matrix.md
          sed -i '4d' doc/src/feature-matrix.md

          # set column properties again (while adding header line)
          sed -i '5i |---|---|---|---|:-:|:-:|:-:|:-:|:-:|' doc/src/feature-matrix.md
          
          # add width fix
          echo '' >> doc/src/feature-matrix.md
          echo '<style>#content main {max-width: unset !important;}</style>' >> doc/src/feature-matrix.md
      - name: Commit changes
        run: |
          git config --global user.name 'Revolt CI'
          git config --global user.email 'revolt-ci@users.noreply.github.com'
          git commit -am "chore(docs): update feature matrix"
          git push
